### ISSUE TITLE
Refactoring Main_Activity structure

### ISSUE THREAD

**Issue by tudorcodrea** [batsw/AndroidAnonymityChat#6]
Reshaping the main_activity.xml structure and all its graphical elements

**Comment by MitelRoxana** [comment]
mTorStatus = (TextView) findViewById(R.id.tor_status);

//set text programmatically
mTorStatus.setText("Stopped");

//change text color programmatically
mTorStatus.setTextColor(getResources().getColor(R.color.colorStoppedTorStatus));

**Comment by tudorcodrea** [comment]
The Open Port and Connect To Partner buttons elements are connected to the backend and functional as well as their corresponding edit text elements.

**Comment by tudorcodrea** [comment]
It remains only to rearrange them on the view.

**Comment by tudorcodrea** [comment]
Testing done, everything works as expected.
